### ISSUE TITLE
Make assignments with '=' 1 token, commands with options don't work

### ISSUE THREAD

**Issue by STROBOLKOP** [P-Claus/minishell#7]
Currently the equals sign is not part of the token and is instead used a delimiter. This breaks things for options to commands.
Example I encountered this in:
git diff --word-diff=color

Tokens are 'git' 'diff' '--word-diff' 'color'. Making it as 1 token would be 'git' 'diff' '--word-diff=color', giving the argument correctly to the command.

As a bonus for this change, adding variable could now be easier by using the previously implemented functions made to load in the envp for the environment list as it already expects variables in the form of 'name=value'.

**Comment by P-Claus** [comment]
Issue is fixed. 

The command is split into three tokens:
- git
- diff
- --word-diff=color

This works, but the '=' is not used as a delimiter anymore and name=value is one token instead of two ('name', 'value').

Will wait to merge until we are sure this is what we want.
